name: Pythonpytest 
on:
  push:
  pull_request:
    branches:
      - master
    
jobs:
    pythonmoduletester:
        runs-on: ubuntu-latest  
        defaults:
            run: 
                working-directory: ./2021-personal-self-study/python_lib/python      
        steps:
          - name: Checkout
            uses: actions/checkout@v2 
          - name: Set up Python 3.8.3
            uses: actions/setup-python@v2
            with:
                python-version: '3.8'     
          - name: Install dependencies   
            run: |
              sudo apt-get install python3-pip
              pip install -r requirements.txt
              pip install -e .
          - name: run pytest
            run: |
              python -m pytest --exitfirst
            